file=open("ap","w")
file.write("yoo hi there")
file.close()
file=open("ap","r+")
file.write("llkkl lllkkkjjkffsd sdjhfbsjhfbj shgdvfhsgvf")
file.seek(0)
s=(file.read())
file.close()
file=open("k","w")
file.close()
file=open("k","r+")
file.write(s)
file.seek(0)
print(file.read())
file.close()